name: CI 
on:
 push:
   branches:
      - main
permissions:
  contents: read
  id-token: write
env:
  ECR: ${{ secrets.ECR }}
  SERVICE: flask 
jobs:
 build:
   name: Building docker image
   runs-on: ubuntu-latest
   steps: 
    - name: Checkout Code
      uses: actions/checkout@v4
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::767397770552:role/gitbubaction-ecr-role
        aws-region: ${{ vars.AWS_REGION }}
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build Docker image
      run: |
        TAG=${GITHUB_SHA::7}
        aws ecr get-login-password --region $AWS_REGION \
              | docker login --username AWS --password-stdin $ECR
        docker build  -t $ECR/$SERVICE:$TAG .
        docker push $ECR/$SERVICE:$TAG
        #echo "image=$ECR/$SERVICE:$TAG" >> "$GITHUB_OUTPUT" 
