apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: 
  name: flask-secrets
  namespace: uat
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: flask-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef: 
        key: rds!db-e435a13f-a48e-43fb-8da8-f1872d8d8938
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef: 
        key: rds!db-e435a13f-a48e-43fb-8da8-f1872d8d8938
        property: password