apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: flask-secrets
  namespace: {{ .Values.namespace }}

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore.name }}
    kind: {{ .Values.externalSecret.secretStore.kind }}

  target:
    name: {{ .Values.externalSecret.target.name }}
    creationPolicy: Owner

  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: username

    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: password